[context.development]
base_url = "https://api.anthropic.com/dev"
auth_token = "dev-token"

[context.staging]
base_url = "https://api.anthropic.com/staging"
auth_token = "staging-token"

[context.production]
base_url = "https://api.anthropic.com/prod"
auth_token = "prod-token"